http://localhost:8001/services
Accept: application/json

#####
http://localhost:8000/api/gists
Accept: application/json

######
http://localhost:8001/status
Accept: application/json

###
http://localhost:8000/hello/elvis
Accept: application/json

###
# http://localhost:8080/hello/elvis
# Accept: application/json

###
http://localhost:8000/status
Accept: application/json

###
http://localhost:8000
Accept: application/json