version: '3.7'
services:
  # logspout:
  #   image: gliderlabs/logspout:v3
  #   command: 'raw+udp://logstash:5000'
  #   environment: 
  #     - EXCLUDE_LABEL=logspout.exclude
  #     # - RAW_FORMAT="container {{ .Container.Name }}"
  #   # links:
  #   #   - logstash
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #   labels: 
  #       logspout.exclude: true
  #   depends_on:
  #     - elasticsearch
  #     - logstash
  #     - kibana
  logstash:
    image: logstash:7.14.1
    environment:
      - STDOUT=true
    # links:
    #   - elasticsearch
    volumes: 
      - ./pipeline.conf:/pipeline.conf
      - ./patterns:/patterns
    labels: 
      logspout.exclude: true
    depends_on:
      - es-node
      - kibana
    command: bash -c "logstash -f /pipeline.conf"
    ports: 
      - 5000:5000
  kibana:
    image: kibana:7.10.2
    # links:
    #   - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://es-node:9200
      - ELASTICSEARCH_HOSTS=http://es-node:9200
    ports:
      - '5601:5601'
    labels: 
      logspout.exclude: true
    depends_on:
      - es-node
  # elasticsearch:
  #   image: elasticsearch:7.14.1
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   labels: 
  #     logspout.exclude: true
  #   environment:
  #     ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  #     http.host: "0.0.0.0"  
  #     transport.host: "127.0.0.1"
  es-node:
    image: es-node:7.10.2
    environment:
      cluster.name: odfe-cluster
      node.name: es-node
      # - discovery.seed_hosts=es-node
      # - cluster.initial_master_nodes=es-node
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      http.host: "0.0.0.0"  
      transport.host: "127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    # volumes:
    #   - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    labels: 
      logspout.exclude: true

networks:
    default:
      # Use a custom name
      name: elk-network1