version: '3.7'
services:
  # logspout:
  #   image: gliderlabs/logspout:v3
  #   command: 'raw+udp://logstash:5000'
  #   environment: 
  #     - EXCLUDE_LABEL=logspout.exclude
  #     # - RAW_FORMAT="container {{ .Container.Name }}"
  #   # links:
  #   #   - logstash
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #   labels: 
  #       logspout.exclude: true
  #   depends_on:
  #     - elasticsearch
  #     - logstash
  #     - kibana
  logstash:
    image: logstash:7.14.1
    environment:
      - STDOUT=true
    # links:
    #   - elasticsearch
    volumes: 
      - ./pipeline.conf:/pipeline.conf
      - ./patterns:/patterns
    labels: 
      logspout.exclude: true
    depends_on:
      - elasticsearch
      - kibana
    command: 'logstash -f /pipeline.conf'
    ports: 
      - 5000:5000
  kibana:
    image: kibana:7.14.1
    # links:
    #   - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
    labels: 
      logspout.exclude: true
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - '9200:9200'
      - '9300:9300'
    labels: 
      logspout.exclude: true
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      http.host: "0.0.0.0"  
      transport.host: "127.0.0.1"
networks:
    default:
      # Use a custom name
      name: elk-network